import { useState } from 'react'
import { WaveformCanvas } from './components/WaveformCanvas'

function App(): JSX.Element {
  const [port, setPort] = useState<string>('')
  const [connectedPort, setConnectedPort] = useState<string>('')

  return (
    <div style={{ display: 'flex', flexDirection: 'column', fontFamily: 'sans-serif', backgroundColor: '#111', width: '100%', height: '100%' }}>
      {!connectedPort && (
        <div style={{ padding: '20px' }}>
          <h2 style={{ color: 'white' }}>Scryer Waveform Debugger</h2>
          <div style={{ marginBottom: '20px' }}>
            <label style={{ color: 'white', marginRight: '10px' }}>Backend Port:</label>
            <input 
              type="text" 
              value={port} 
              onChange={e => setPort(e.target.value)} 
              placeholder="e.g. 54321" 
            />
            <button 
              onClick={() => setConnectedPort(port)}
              style={{ marginLeft: '10px', padding: '4px 10px' }}
            >
              Connect
            </button>
          </div>
          <p style={{ color: '#888' }}>Enter the port generated by the backend server and click Connect.</p>
        </div>
      )}
      
      {connectedPort && (
        <WaveformCanvas port={connectedPort} />
      )}
    </div>
  )
}

export default App
